### ISSUE TITLE
Username fields

### ISSUE THREAD

**Issue by smachi** [pdme/gravity-forms-polylang#2]
The plugin is removing the advanced username fields' input boxes

**Comment by pdme** [comment]
Can you be more specific? I tested with an advanced name field, but everything seems to work fine.

**Comment by smachi** [comment]
It's not with the advanced Name field, it's with the advanced Username field (note that are distinct fields).

If you add a username field and save the form all seems right, but if you go out from the form settings page and go back, the username input box has gone (same as in the front form display).

And if you then disable the "Integrate Gravity Forms + Polylang" plugin and go back to the form where you added the username field, you'll see that the input box is back again.

**Comment by pdme** [comment]
I don't see a username field in the list of available fields. Do you have another plugin installed? Or Gravity Forms add-on?

**Comment by smachi** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/6269226/19641907/166c0928-99e3-11e6-8c9d-1256d0c103ac.png)

GravityForms of course. Check my screenshot.

**Comment by pdme** [comment]
It seems you have the user registration add-on installed. Check your plugins.

**Comment by smachi** [comment]
Yes I have that addon too, what's the problem with it?

**Comment by pdme** [comment]
I asked if you had any other plugins installed.

In any case, I will look into it.

**Comment by smachi** [comment]
Oh, I'm sorry, I understood that you were asking if I was using GravityForms.

No problem, thanks for your help.

**Comment by pdme** [comment]
I finally had some time to look into this.

It seems to be a Gravity Forms bug. I've opened a support ticket with them.

Will keep you posted.

**Comment by pdme** [comment]
It wasn't a GF bug in the end, but an issue of race condition. Updated repo and plugin. Closing this as fixed.
