### ISSUE TITLE
Language tag

### ISSUE THREAD

**Issue by szepeviktor** [pdme/gravity-forms-polylang#6]
Hello @pdme !
Is it possible to add a language tag like `{admin_email}` which will specify the current language in the notification email?

And to have a language field to be used e.g. in Zoho CRM Add-On?

**Comment by pdme** [comment]
Hi @szepeviktor ,

Sorry for my late reply - I somehow didn't get notified.

I'm sure that this is possible, but I currently don't have the time to implement it. It also seems a bit of an edge case.

Feel free to fork and make a pull request!
