### ISSUE TITLE
Option to not translate input values

### ISSUE THREAD

**Issue by moritzbappert** [pdme/gravity-forms-polylang#7]
Hey there, 
thanks for the helpful plugin! 

I would love to have the option to modify the whitelist from outside of the plugin without modifying the plugin. Could you implement something like that, i think a filter might suffice? 

I have a dropdown of countries that should have translated option labels but the option values need to stay the same...

Thanks a lot
Moritz

**Comment by pdme** [comment]
I'm sorry, I currently don't have the time to do this. Feel free to contribute with a PR!
